FROM ubuntu:16.04
RUN apt-get update

# Install Ansible
RUN apt-get install python-pip python-dev git python-yaml python-paramiko -y
RUN pip install jinja2

RUN cd ~ && \
    git clone https://github.com/ansible/ansible.git && \
    cd ansible && \
    git checkout v2.0.1.0-1 && \
    git submodule update --init --recursive && \
    make install && \
    mkdir /etc/ansible

# Install Ansible inventory file
RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts
